<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baduykiemthu</name>
   <tag></tag>
   <elementGuidId>907127bf-bda3-4c15-a539-43fa02dfb94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr/th/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.field-username > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db873390-a8b5-401a-9710-d5169b96d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/2/change/</value>
      <webElementGuid>4280386e-b16f-48a4-bef8-7adcc1d77c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baduykiemthu</value>
      <webElementGuid>43bc89d6-7941-40a1-818a-f99dba4c8ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[1]/th[@class=&quot;field-username&quot;]/a[1]</value>
      <webElementGuid>9710127a-7fee-4865-b480-3b48f7bebf18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr/th/a</value>
      <webElementGuid>480f383c-8afb-4d6a-918a-5d5815f566b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'baduykiemthu')]</value>
      <webElementGuid>97029de5-e3df-4af7-824c-c7803858f63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/following::a[1]</value>
      <webElementGuid>072ccfa0-3624-4b1a-ad25-277764373fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::a[2]</value>
      <webElementGuid>9d00192b-ddb5-4435-83b5-1cb9273fadaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nbduy@ctuet.edu.vn'])[1]/preceding::a[1]</value>
      <webElementGuid>9eabb5a1-f1bb-4977-89bf-69c25c574d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duy'])[1]/preceding::a[1]</value>
      <webElementGuid>16ca685d-fecb-40bb-8664-cc31b5c700a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='baduykiemthu']/parent::*</value>
      <webElementGuid>2f7463a6-d98a-4f00-a970-da3866b5f772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/auth/user/2/change/')]</value>
      <webElementGuid>79c97dfe-4337-4988-b832-df8bb48da060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr/th/a</value>
      <webElementGuid>dbe5cc1e-6909-41d0-ace6-068a8f3bd9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/2/change/' and (text() = 'baduykiemthu' or . = 'baduykiemthu')]</value>
      <webElementGuid>721b14ef-f917-4d83-a515-c220bf059135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
