<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Active</name>
   <tag></tag>
   <elementGuidId>97338770-ca7a-4e00-b723-9e145b2ff93b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.vCheckboxLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='user_form']/div/fieldset[3]/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4360538a-55ba-4374-baa8-f8e3bbecb3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vCheckboxLabel</value>
      <webElementGuid>f40490de-1ca5-4bb9-9964-5b8f52b613cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id_is_active</value>
      <webElementGuid>451c1dff-8d00-4c32-817f-e4879d205883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>2c7e8fd1-afcb-4df1-9fbe-4d89c028e800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_form&quot;)/div[1]/fieldset[@class=&quot;module aligned&quot;]/div[@class=&quot;form-row field-is_active&quot;]/div[1]/div[@class=&quot;flex-container checkbox-row&quot;]/label[@class=&quot;vCheckboxLabel&quot;]</value>
      <webElementGuid>57366b91-9ef3-4479-b3c1-edbe7e099b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div/div/div/label</value>
      <webElementGuid>41f85501-6dd3-4eda-a5fc-4d0dada02e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/following::label[1]</value>
      <webElementGuid>4dc494f0-7940-43d9-a363-6cbbe904f171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address:'])[1]/following::label[1]</value>
      <webElementGuid>4325c62c-4c24-4844-8369-dd14ceb93811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/preceding::label[1]</value>
      <webElementGuid>a85775e8-ac8b-4e39-9222-79326c01cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Designates whether the user can log into this admin site.'])[1]/preceding::label[2]</value>
      <webElementGuid>c1526fe2-3ce9-4742-b406-bdffeaee0c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>904c2aa8-9613-4b43-9a24-3be3ea7e0893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/label</value>
      <webElementGuid>fa5b0ee0-efca-4fe4-90aa-c2832ed848dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>92d72c0a-c6e7-4759-8235-c8ca84d16d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
