<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go_action-toggle</name>
   <tag></tag>
   <elementGuidId>757c7b82-188e-4ede-a52f-a2efd861cc7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='action-toggle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>781251f9-0a3a-4e4a-b7e8-90027f4990e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7287bb01-a9b2-4fe4-9d58-91c8fcfe48f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-toggle</value>
      <webElementGuid>d499f546-5ac6-47e5-976d-d906234545cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select all objects on this page for an action</value>
      <webElementGuid>9dee3011-efb7-4589-91f9-7b7685954992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-toggle&quot;)</value>
      <webElementGuid>4e811801-574a-48fa-a72f-45c4eb77210a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='action-toggle']</value>
      <webElementGuid>4660dff8-7227-46a9-b303-35839423dabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/thead/tr/th/div/span/input</value>
      <webElementGuid>3fca7730-5ce4-44dd-bc90-6ccdfc1cf280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>94f16817-e40b-488b-bdd1-d3c135bdb81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'action-toggle']</value>
      <webElementGuid>eaa1a9d6-d98d-4044-b097-c00e6a158446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
