<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Edit_Category</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d598c58b-d22b-46b5-ad8c-1b1df8f90a3b</testSuiteGuid>
   <testCaseLink>
      <guid>e757255a-3c9e-4dc2-8cef-e2f1709c84b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit_Category</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f01c8b3d-b2e6-488f-bde9-68bcccf9e864</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_edit_category</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f01c8b3d-b2e6-488f-bde9-68bcccf9e864</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>b7a25991-47a8-4c9c-8feb-b6ea2dcb22e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f01c8b3d-b2e6-488f-bde9-68bcccf9e864</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Slug</value>
         <variableId>3fb7be23-a1cd-419a-a1a8-011dfd779adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f01c8b3d-b2e6-488f-bde9-68bcccf9e864</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Res</value>
         <variableId>128c7ff6-376b-49de-adbc-2791a9e07c44</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
