<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_is_staff</name>
   <tag></tag>
   <elementGuidId>c05f1bf4-bc2f-4243-8a41-a93130911352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_staff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_staff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e135ee9-99c1-4e33-8406-a57bea842063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>35d432e1-7c52-48f4-9403-1dc4bad1be37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_staff</value>
      <webElementGuid>44435176-1fa2-4161-b1b6-0d04bfc7af83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_staff_helptext</value>
      <webElementGuid>68b39277-d0b7-47e6-876a-814a59ab39b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_staff</value>
      <webElementGuid>6921362d-065b-450a-909b-f09793de6e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_staff&quot;)</value>
      <webElementGuid>f8026fd9-5c41-43e7-b79e-59b017b6266b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_staff']</value>
      <webElementGuid>d133c2b5-f8a0-4436-9298-d78755f676dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>b0cd28d2-d03c-49f3-9214-43e4b5746947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>d67a1bf0-b7b4-428e-bde4-ef548b99dd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_staff' and @id = 'id_is_staff']</value>
      <webElementGuid>9471ab8f-ba9d-4876-9ab1-fc91981983f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
