<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Permissions_is_active</name>
   <tag></tag>
   <elementGuidId>0729b262-1552-4894-907a-f5d5106ddc33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_active']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f48ec5d7-c7f5-43fd-b7fb-2c5b01e21066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b4efedb-509b-4017-859c-b7be7f809f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_active</value>
      <webElementGuid>31399851-2cd3-4bb0-b159-bd846d8dfc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_active_helptext</value>
      <webElementGuid>c41e4d60-6a38-46a9-86bb-78b0ed59f01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_active</value>
      <webElementGuid>e27ac3a2-4f15-4461-8327-3e95e34b3a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_active&quot;)</value>
      <webElementGuid>14a713e9-ff9e-4059-9e19-4dc74a008761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_active']</value>
      <webElementGuid>d04c102f-9a96-4175-8d2a-e6484b1a6e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div/div/div/input</value>
      <webElementGuid>8620dddd-8908-46c3-bb1a-2e066a2fbc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/input</value>
      <webElementGuid>113526ff-9382-4756-ba54-ca0af6c3fc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_active' and @id = 'id_is_active']</value>
      <webElementGuid>17f94cbb-0f13-496c-a8cd-d99896b601c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
