<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designates whether the user can log i_33faa1</name>
   <tag></tag>
   <elementGuidId>6ca7239f-72da-4404-98ff-9f267ac25120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_superuser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_superuser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a6f97df-65a6-46a7-931d-09fd78cc1aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e923b138-f4c2-4379-9c06-017422ad2125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_superuser</value>
      <webElementGuid>f22fc4ac-24c1-4712-bcd3-6889d8951601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_superuser_helptext</value>
      <webElementGuid>5a66dbcd-41d3-4878-88ed-e591ab5a718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_superuser</value>
      <webElementGuid>c732d749-de83-4a7b-9b3a-816a847939c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_superuser&quot;)</value>
      <webElementGuid>9754a9c3-5f78-4282-9d3b-6ac853982c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_superuser']</value>
      <webElementGuid>12a5c603-6315-495a-876f-11418d5d3601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[3]/div/div/input</value>
      <webElementGuid>88774642-9b3d-4d8f-a7de-a0c6a1837893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div/div/input</value>
      <webElementGuid>d57fa992-b742-484c-a732-4524373bfc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_superuser' and @id = 'id_is_superuser']</value>
      <webElementGuid>ebf8d909-1f9b-4073-8983-b0220d1d64b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
