<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Staff status_action-checkbox</name>
   <tag></tag>
   <elementGuidId>0e60855b-75f8-4e5b-83fc-4d8eaf773599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>54da9f9a-d05d-4660-ad0c-aeb27546b176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-checkbox</value>
      <webElementGuid>c8dd23d4-c5b4-4388-b7b4-b7e841d9fd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[1]/td[@class=&quot;action-checkbox&quot;]</value>
      <webElementGuid>719fc9f3-dbe9-4e13-9412-fecce50b7bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr/td</value>
      <webElementGuid>5840dff1-5984-47e1-b007-5dae5c97c29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/following::td[1]</value>
      <webElementGuid>2d29e527-286e-4839-b731-d8cd6e41c27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::td[1]</value>
      <webElementGuid>3f8966b0-073b-4510-ae79-0aed37e14304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='baduy'])[1]/preceding::td[1]</value>
      <webElementGuid>2cfb5719-a2f3-47f7-babc-41202b48cce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>ce8bf899-b0db-4149-a3c6-6541859a06c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr/td</value>
      <webElementGuid>509ce650-0717-4fb2-98f0-b98680e29ceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
