<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>6282f029-69a9-40b8-8d9e-a3f4ac0b1c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.model-user > td:nth-of-type(2) > a.changelink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2edc7a11-31c6-4a4c-a69e-970dcf1142f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/</value>
      <webElementGuid>d0cf1fdb-10a6-41e1-b500-6ed2953d9db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changelink</value>
      <webElementGuid>12af79bc-ed2e-4fa5-9cb9-f4963caa6dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>auth-user</value>
      <webElementGuid>ab15c2c5-dcc4-450a-bfc1-76d678c79d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>769972f3-38e2-4c58-a244-80d73ab05d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;app-auth module&quot;]/table[1]/tbody[1]/tr[@class=&quot;model-user&quot;]/td[2]/a[@class=&quot;changelink&quot;]</value>
      <webElementGuid>74810af1-ff24-4912-9b10-a7d134f5917f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>29a3d163-f4e7-40f5-b09d-a24fb4e35c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Change')])[5]</value>
      <webElementGuid>c8b8be24-62ca-4809-afa0-6dc1bcee177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::a[1]</value>
      <webElementGuid>f299cd47-30e8-49ee-9e7f-cd2a577946f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>7d5e39c9-dbf4-4cfc-b326-6a03d3450fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent actions'])[1]/preceding::a[1]</value>
      <webElementGuid>dddf0d8f-ad99-4a12-9843-2813f5f51e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My actions'])[1]/preceding::a[1]</value>
      <webElementGuid>aec3011d-069a-464c-a6bd-3bf53a55506f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/admin/auth/user/')])[3]</value>
      <webElementGuid>44c1ae48-3ed8-4004-80c5-04f2b90150bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>fd7cc6c4-dc09-4972-a55a-85ebb6e96599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>0a22a6a8-1e51-4dea-a6e7-3aeccfb87d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
