<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add</name>
   <tag></tag>
   <elementGuidId>ae9d35bf-6b3c-425b-9603-eeedb72bf3a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.model-user > td > a.addlink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de890948-f23c-4724-a8a0-e74459bd9e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/add/</value>
      <webElementGuid>2b7012f6-d399-4d5a-8649-3801e77ba22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addlink</value>
      <webElementGuid>41751f7d-6d5c-48c4-8338-ccb8476a643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>auth-user</value>
      <webElementGuid>60d4a5c9-0faa-472d-826d-97a3e7734979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>a429ebbf-d612-460d-8bee-2cad36b158a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;app-auth module&quot;]/table[1]/tbody[1]/tr[@class=&quot;model-user&quot;]/td[1]/a[@class=&quot;addlink&quot;]</value>
      <webElementGuid>303b987d-b07a-4dce-8786-c20b765dfe76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>269e1f4a-79c5-47b2-b958-ed6185113d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add')])[4]</value>
      <webElementGuid>0b3a2255-4d48-4776-a6fb-dfea9e024aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[1]</value>
      <webElementGuid>82bd206e-88de-428e-8777-938da84989dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[3]/following::a[2]</value>
      <webElementGuid>4dcfff40-d25b-4956-9d96-700e09b158c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[4]/preceding::a[1]</value>
      <webElementGuid>b8aac311-a20d-401a-8674-cd58828d5f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent actions'])[1]/preceding::a[2]</value>
      <webElementGuid>f17c3408-621e-41bb-9bb2-ba1bd677d077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/auth/user/add/')]</value>
      <webElementGuid>5ee1f589-3292-4a1f-8c10-b4975727721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>0cc04542-4004-4512-a4bf-1f1597d3684c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/add/' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>6c71bd66-2b05-4ce0-936c-9fc67bc59510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
