<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>bc2da24e-514b-4fd4-ab2d-77ab6c51da4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.model-user > td:nth-of-type(2) > a.changelink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05c72793-f286-44ae-b3db-a0a9a6996fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/</value>
      <webElementGuid>a5072317-4c38-4045-88d8-11f19b8a8e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changelink</value>
      <webElementGuid>68be269f-aedc-4e47-9247-b177a9718695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>auth-user</value>
      <webElementGuid>4f4babeb-5fd1-4c35-9c2a-82e8d13e3976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>c60a2653-2ba8-4b94-98eb-bc479fe61ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;app-auth module&quot;]/table[1]/tbody[1]/tr[@class=&quot;model-user&quot;]/td[2]/a[@class=&quot;changelink&quot;]</value>
      <webElementGuid>eadad7d4-a974-4f8d-8ef0-adbbcb18ccff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>0dc16aaf-3b1d-44ff-b8f1-2af7662974f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Change')])[5]</value>
      <webElementGuid>94169675-0ec3-4c60-a7aa-4a7da66808ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::a[1]</value>
      <webElementGuid>a5dbf265-44a3-4b08-8117-77f2f0a353d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>25866675-a8fc-4f7c-a2cc-719a13fb50f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent actions'])[1]/preceding::a[1]</value>
      <webElementGuid>9cf36301-5b78-445b-b49f-d77ffe811b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My actions'])[1]/preceding::a[1]</value>
      <webElementGuid>a892e205-d056-4ea1-8d62-a07c01db9ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/admin/auth/user/')])[3]</value>
      <webElementGuid>a8ddd2ad-4169-465b-9974-2c7ec26f27cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>7ac2a1c6-38a4-426f-899c-298546932c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>e7cb58c3-2439-40eb-ba67-aad945021b8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
