<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Permissions_is_active</name>
   <tag></tag>
   <elementGuidId>6318a9dc-e393-49fd-b116-248d11c5a85f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_active']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>981b4490-4dec-4ae2-98e3-6d422a149de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bf782b0b-d5bc-494b-958d-e3652666a673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_active</value>
      <webElementGuid>25afc28d-738f-46cb-bf9e-1946c60625f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_active_helptext</value>
      <webElementGuid>936bf214-77fb-4b74-aa59-d4063202c240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_active</value>
      <webElementGuid>42f0d552-6b56-4345-b8c4-901efa42db9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_active&quot;)</value>
      <webElementGuid>4483cd69-b65e-4296-ba46-bfbf6282a39f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_active']</value>
      <webElementGuid>20326248-386b-4b65-83e1-19ad661eec6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div/div/div/input</value>
      <webElementGuid>9d2faad9-232a-41aa-8601-908b9a806da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/input</value>
      <webElementGuid>0ba5656d-0231-41e8-95bf-472cc34b0b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_active' and @id = 'id_is_active']</value>
      <webElementGuid>625398cb-490c-4b6a-a398-fcc4ec208d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
