<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_is_staff</name>
   <tag></tag>
   <elementGuidId>1c67004a-c6b7-4334-bb81-3374a4bde9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_staff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_staff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4217b790-e0e3-4722-83e7-2a843f323f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7d6120ea-4ccf-4011-a198-276597a721e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_staff</value>
      <webElementGuid>4d80178d-a19a-4b63-9f10-5ce04d3f1f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_staff_helptext</value>
      <webElementGuid>6cdb5a85-3f18-46d4-a151-10bf2b46d578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_staff</value>
      <webElementGuid>c553b34f-23b8-48ba-9f3a-59e5295313b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_staff&quot;)</value>
      <webElementGuid>64afba3c-26a7-49e8-8916-05d6ce2546fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_staff']</value>
      <webElementGuid>f73c102c-f1fd-49e4-b6fe-5c61fcba11f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>a77ddcd4-ecc4-4015-98bd-6bcaacfb5487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>5d37d5e2-3039-4bf7-997e-b944aa972e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_staff' and @id = 'id_is_staff']</value>
      <webElementGuid>ab2eec4d-e6f4-4bf9-a8d7-35e0917f1197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
