<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Note You are 7 hours ahead of server _4695a7</name>
   <tag></tag>
   <elementGuidId>62fcd159-fa63-43b6-b07c-19bcee2b71b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4f751d3-965f-40cc-bf06-f1ae21478f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5fe75af7-64ef-4289-8b78-655500f7b073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>601baed5-76f2-4e1d-aa79-e4ed6f7ba70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>a78261fc-847f-48e0-8c79-3df09c5cce4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_save</value>
      <webElementGuid>b646cfa9-d723-4c19-982a-e103fc29ef65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_form&quot;)/div[1]/div[@class=&quot;submit-row&quot;]/input[@class=&quot;default&quot;]</value>
      <webElementGuid>96df3121-5a4d-40c0-b413-cdf7517ac0fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_save']</value>
      <webElementGuid>6ff41ef5-20cc-4da1-8648-8847335f8b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/div/input</value>
      <webElementGuid>81a6f5db-593f-43c5-8873-056ea8f940f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>e6d73bdc-f4a5-42a4-8e36-0ded324d48e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = '_save']</value>
      <webElementGuid>a2d4cf18-0d36-4958-85a7-18672ed17ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
