<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baduykiemthu</name>
   <tag></tag>
   <elementGuidId>25ff49b0-89e4-43fc-b572-3888037ff656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.field-username > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr/th/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fc92c9b-c4f1-4e5f-9f98-b67d6c95828b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/2/change/</value>
      <webElementGuid>3a77f458-c26e-4304-91ed-ed48a273575e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baduykiemthu</value>
      <webElementGuid>bb1e0f42-79dd-4efe-889f-0fc86c73602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[1]/th[@class=&quot;field-username&quot;]/a[1]</value>
      <webElementGuid>95c6ada9-0192-4686-8278-2013b59be6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr/th/a</value>
      <webElementGuid>f19e65cb-7e53-4a82-8141-dfae38ee0650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'baduykiemthu')]</value>
      <webElementGuid>91ecb51a-784a-4c4c-a7e0-7bf51d059634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/following::a[1]</value>
      <webElementGuid>3bb5ff69-e347-4bd3-a4cb-f4a6cfe3d7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::a[2]</value>
      <webElementGuid>0a645baf-2bef-42b4-a58f-4cbb73ab9dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nbduy@ctuet.edu.vn'])[1]/preceding::a[1]</value>
      <webElementGuid>f9f7986c-4a98-4d6a-899f-1324ed038463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duy'])[1]/preceding::a[1]</value>
      <webElementGuid>6daf56df-c5e1-4fbd-9f59-7f5f6d1c0681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='baduykiemthu']/parent::*</value>
      <webElementGuid>3c078085-e1a8-4e42-9d98-d2648fd18d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/auth/user/2/change/')]</value>
      <webElementGuid>b2271609-ba25-408d-9c4a-4657376da849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr/th/a</value>
      <webElementGuid>dd3f0edf-85c0-4f20-b635-b778ceb132ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/2/change/' and (text() = 'baduykiemthu' or . = 'baduykiemthu')]</value>
      <webElementGuid>477ddf0c-c083-4887-82ea-1b870a417eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
