<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>1de33487-281a-4034-a25a-4109554cea33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.changelink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-main']/div/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b056f72-18cd-412f-a9e9-f1d7dfe9690d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/app/categogy/</value>
      <webElementGuid>d91bb030-4320-43cf-82b2-41210a511752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changelink</value>
      <webElementGuid>19ba9ca0-115e-4169-8a9c-b837796dc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>app-categogy</value>
      <webElementGuid>992fdc73-e9e0-415c-be12-308dce6dba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>25234d61-4aee-4509-bcb5-d62106b3cde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;app-app module&quot;]/table[1]/tbody[1]/tr[@class=&quot;model-categogy&quot;]/td[2]/a[@class=&quot;changelink&quot;]</value>
      <webElementGuid>8ac09a7c-65b9-43fe-8d09-9aab161e93b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-main']/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>f486158e-ac4e-4acf-aaee-96dd0d90781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Change')])[2]</value>
      <webElementGuid>52b53a1a-5ff4-4797-943f-3d6bbb8f5e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::a[1]</value>
      <webElementGuid>78bfe6d6-50a3-42e7-842e-30b23700dd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categogys'])[1]/following::a[2]</value>
      <webElementGuid>03d20ca9-079f-4d15-8ffa-9688d6cbb928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::a[1]</value>
      <webElementGuid>65624a37-01b2-429e-bb62-e0b5ec657a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::a[2]</value>
      <webElementGuid>c4bea96c-8808-4bfd-80ef-4df5ab4f9e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>0ee20493-dee9-4d4c-8446-be8ff140d969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/admin/app/categogy/')])[3]</value>
      <webElementGuid>e5275731-dfe5-4f2b-a2b9-49cd13c7a67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>4e741350-8cb1-442c-ac79-8200e44e7baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/app/categogy/' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>a14bd9c3-908d-4c55-a642-4108e208f0fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
