<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ipad 9 Pro_action-checkbox</name>
   <tag></tag>
   <elementGuidId>06795f0d-655c-4525-af9d-da9b47d15746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.action-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5b278d44-7de1-4593-8057-549141559f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-checkbox</value>
      <webElementGuid>8e06d3cd-030c-43e5-9dc8-f947dc4c93b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[2]/td[@class=&quot;action-checkbox&quot;]</value>
      <webElementGuid>bb372e76-2d16-40fb-b42c-7a0d9c73ff6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr[2]/td</value>
      <webElementGuid>e48ea808-b74a-4e82-b899-01aa061f33c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ipad 9 Pro'])[1]/following::td[1]</value>
      <webElementGuid>55943f42-ff06-4b84-a7dc-b068d8bfb9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::td[2]</value>
      <webElementGuid>7cc842ca-78d8-4c78-8aa9-12f996f0905c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung Galaxy S23'])[1]/preceding::td[1]</value>
      <webElementGuid>0b09f351-231d-48d0-9be6-48a538f3ff1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung Galaxy S20'])[1]/preceding::td[2]</value>
      <webElementGuid>cf36431b-c025-44e4-8c9c-e12778587ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr[2]/td</value>
      <webElementGuid>8e193c95-f998-4baf-87d3-4b3eb6558ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
