<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_is_staff</name>
   <tag></tag>
   <elementGuidId>61f38fdc-8948-4c95-8698-df393ad8a79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_staff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_staff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de02a40d-c5e2-43e9-92a5-d6ff7e875b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a0d4eba4-625e-4214-8a1c-85cdeb556b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_staff</value>
      <webElementGuid>55db5681-8b4f-4986-b16b-e59dacc73ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_staff_helptext</value>
      <webElementGuid>70d702c5-a6b8-4614-aa00-f5977197ba41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_staff</value>
      <webElementGuid>31807b0e-5991-467b-9421-568fc3b6d3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_staff&quot;)</value>
      <webElementGuid>c5e57fef-3fd7-4b1a-b9cb-2ccec25d6465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_staff']</value>
      <webElementGuid>a3019ffa-65c8-410b-b1f4-e461449f73b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>cafa3296-755a-4999-aa34-d1af4f7c6f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>fb1a5465-e053-4a7c-bc7c-11dd317f5f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_staff' and @id = 'id_is_staff']</value>
      <webElementGuid>b2d835c4-8216-485e-bbf0-14bc0c467d87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
