<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Categogys</name>
   <tag></tag>
   <elementGuidId>2b8e49cf-af83-4f37-a136-122daf078dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='app-categogy']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app-categogy > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>583ba0e5-3aa1-4884-976b-408a5857396f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/app/categogy/</value>
      <webElementGuid>f6b040b6-74cc-4ba3-9ef5-c1cc7f5e1331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categogys</value>
      <webElementGuid>6804831d-cf58-427e-bab4-8458ab476170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-categogy&quot;)/a[1]</value>
      <webElementGuid>69285ea4-0c6a-499a-87eb-dced48e7aaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='app-categogy']/a</value>
      <webElementGuid>1ecfb9d3-51c3-41d4-8df7-13c47cd8ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Categogys')]</value>
      <webElementGuid>99d3a81b-b7e6-418b-86d6-9463d8f02536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App'])[1]/following::a[1]</value>
      <webElementGuid>76e48eb7-6cde-444b-9eda-00aad6797b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site administration'])[1]/following::a[2]</value>
      <webElementGuid>5ede4f6b-459d-4547-944d-27f5df753e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::a[1]</value>
      <webElementGuid>8c81cd26-838e-486c-8427-bb3da7587d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/preceding::a[2]</value>
      <webElementGuid>eb80c1a1-3922-4a46-87e1-0e1bef9cd1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Categogys']/parent::*</value>
      <webElementGuid>91eb16fa-34a6-45b4-b5b7-1397116e9204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/app/categogy/')]</value>
      <webElementGuid>e8d8f4ef-1b6f-417e-98da-1164b6b86f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a</value>
      <webElementGuid>a9e66de6-68ac-43d2-8604-7656dba00f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/app/categogy/' and (text() = 'Categogys' or . = 'Categogys')]</value>
      <webElementGuid>ab2b0716-280e-47e2-9c38-0ba95b8f0aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
