<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Categogys</name>
   <tag></tag>
   <elementGuidId>6452720c-a0c5-4e4d-9ef3-43932e1dab9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='app-categogy']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app-categogy > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7e1d4b5-c0fe-4cb9-8a66-e7c812b4b22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/app/categogy/</value>
      <webElementGuid>c75580ae-761a-4e64-ab12-ee7fa9c5ae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categogys</value>
      <webElementGuid>08d14021-f626-4eb1-8d23-9883d7ba3edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-categogy&quot;)/a[1]</value>
      <webElementGuid>a92be2fa-8733-4696-a18c-1a487f4437e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='app-categogy']/a</value>
      <webElementGuid>e4770149-f56c-430c-9e2c-c24f34c77a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Categogys')]</value>
      <webElementGuid>9e4abe02-82cb-45a0-aa67-86aa73d26cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App'])[1]/following::a[1]</value>
      <webElementGuid>59eaa096-0c73-4ff3-a6a6-062290ac11ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site administration'])[1]/following::a[2]</value>
      <webElementGuid>3d80952b-86f8-4a85-bdbe-c71351666d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::a[1]</value>
      <webElementGuid>4457ed87-6012-4edf-87f6-6508babce021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/preceding::a[2]</value>
      <webElementGuid>48ba0f9d-2022-4140-963c-8e6d860bca7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Categogys']/parent::*</value>
      <webElementGuid>61905997-6641-43eb-90b6-110d7da6370c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/app/categogy/')]</value>
      <webElementGuid>73c3fa84-74f4-4e1b-af97-401346c1cca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a</value>
      <webElementGuid>0c1a7cc9-8a8a-4a02-be3f-39d948c8f898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/app/categogy/' and (text() = 'Categogys' or . = 'Categogys')]</value>
      <webElementGuid>e2ae8741-01ef-4384-a2d8-fdff8d62af3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
