<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baduykiemthu</name>
   <tag></tag>
   <elementGuidId>2dd486f7-3228-4796-adc5-c3bbeebb9b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.field-username > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr/th/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb83eaef-4c8b-4beb-8808-f34bd525ef12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/2/change/</value>
      <webElementGuid>3862886b-4a76-496a-afbe-afb3d884403f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baduykiemthu</value>
      <webElementGuid>c75365f9-a8c2-45ee-be63-42b2d04d6bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[1]/th[@class=&quot;field-username&quot;]/a[1]</value>
      <webElementGuid>89508678-9a8c-45d4-a703-c2fcd1c87803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr/th/a</value>
      <webElementGuid>02bfa17c-4986-4870-9d54-36d74c98feb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'baduykiemthu')]</value>
      <webElementGuid>deb70ec7-9435-41d0-92b9-8808b136558c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/following::a[1]</value>
      <webElementGuid>560cd988-516f-4cb9-986d-2f33332cfd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::a[2]</value>
      <webElementGuid>c9fe9679-49ad-4f47-85c6-2d5158675689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nbduy@ctuet.edu.vn'])[1]/preceding::a[1]</value>
      <webElementGuid>ebc7f4ed-714a-4a0b-b163-dc527a8b581d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duy'])[1]/preceding::a[1]</value>
      <webElementGuid>30c0905c-1cc1-4a6a-b5f7-799ba44f3f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='baduykiemthu']/parent::*</value>
      <webElementGuid>eab6a2fb-db64-4ce2-b006-65343be81bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/auth/user/2/change/')]</value>
      <webElementGuid>67dc4102-f86c-4022-8afb-4c8bb50bfc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr/th/a</value>
      <webElementGuid>faaecd29-5ee6-4d27-83c8-79adf50b86c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/2/change/' and (text() = 'baduykiemthu' or . = 'baduykiemthu')]</value>
      <webElementGuid>61b70f77-edff-4ba9-8b89-5c4f5ac6912a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
