<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price_price</name>
   <tag></tag>
   <elementGuidId>8c63f7e1-a405-46e5-bed3-34208cf786de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b311e247-6c3f-414f-9be5-93a25e1c358a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2affabcd-c0ec-4076-80c4-a9e854f79503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>e71b6849-68ba-4c71-93eb-72a9466f28db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>6d518ede-ac9c-4b76-8640-eaf066b97109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_price</value>
      <webElementGuid>aaae78f1-41d4-4278-9c12-a4a9dfa82f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_price&quot;)</value>
      <webElementGuid>f2454845-ea0f-435d-b48d-40da956c1b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_price']</value>
      <webElementGuid>984d8323-c29e-40b1-bc0a-dae8aa8b371f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_form']/div/fieldset/div[3]/div/div/input</value>
      <webElementGuid>94e9811f-2066-465e-88ee-a07493fb9eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>84e228f8-b3c3-4349-b1c7-5fc4592a35ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'price' and @id = 'id_price']</value>
      <webElementGuid>894a9cff-ab3a-42ba-8c08-d0dbced0f91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
