<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Detail_detail</name>
   <tag></tag>
   <elementGuidId>f40d760c-0231-4347-870b-547015a334a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_detail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='id_detail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14d9a189-dff1-4b02-976e-1098ceae94da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>5257bf68-9a54-4b53-9773-fb23d10b821e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>182d8118-849d-47bf-b20f-f467d5747764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4a444131-2776-4795-bb98-e1d1b78ccfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vLargeTextField</value>
      <webElementGuid>3b328255-4234-4cc5-88ef-cf6f2823299a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_detail</value>
      <webElementGuid>e01e26b0-2c5d-467e-90c1-5ca0da5bfe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_detail&quot;)</value>
      <webElementGuid>88dac8d8-25af-4f36-bb55-b3cf7cac05a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='id_detail']</value>
      <webElementGuid>2fd0eccb-272a-4c6c-960b-910a03c6948d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_form']/div/fieldset/div[5]/div/div/textarea</value>
      <webElementGuid>52df98ba-5f46-431d-a2ad-e86f458f1797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d2a8cb1c-d426-44e5-a221-24e95d19d878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'detail' and @id = 'id_detail']</value>
      <webElementGuid>c55745b1-d781-465d-b98a-52d6d0b0bb47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
