<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>762e49ca-38e2-494a-91b3-81675726e41d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.model-user > td:nth-of-type(2) > a.changelink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e3719ca-bb8a-48ef-85fb-febb98affae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/</value>
      <webElementGuid>9ba343e8-87d7-4981-b684-4a124a845de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changelink</value>
      <webElementGuid>c8caecf5-0ee9-4ef6-b6bc-9634c3001c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>auth-user</value>
      <webElementGuid>a50e7c3a-6b2c-4b07-8164-4504e94775b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>68ad8dba-cef4-46b1-a699-3f914dd3a2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;app-auth module&quot;]/table[1]/tbody[1]/tr[@class=&quot;model-user&quot;]/td[2]/a[@class=&quot;changelink&quot;]</value>
      <webElementGuid>df6ee9fc-fd8e-41b8-97d4-9967d1f88e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-main']/div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>e01869c8-39ec-40aa-83c0-ceebf9516701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Change')])[5]</value>
      <webElementGuid>17b66e31-3f20-4251-9f04-98946be06e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::a[1]</value>
      <webElementGuid>b0b71161-70e6-4257-9729-f56bad7bc886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>b4513faa-7ef2-4d8c-bbea-6ab01ed33ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent actions'])[1]/preceding::a[1]</value>
      <webElementGuid>683f081b-6bba-4e04-9f2b-aad773e0d934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My actions'])[1]/preceding::a[1]</value>
      <webElementGuid>6b0ac26e-29d6-4bb8-95e2-6af6284178f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/admin/auth/user/')])[3]</value>
      <webElementGuid>7c36258d-e54e-45dc-8921-5519701fae1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>0843dc31-07b4-4313-a159-b66f12d85a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>d4043150-1aa4-4c50-beca-4e836df21b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
