<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baduykiemthu</name>
   <tag></tag>
   <elementGuidId>82a30863-2b12-4a11-a52c-b208856d331c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.field-username > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result_list']/tbody/tr/th/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d998c015-c60b-47e3-8acf-0f4e770c4a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/auth/user/2/change/</value>
      <webElementGuid>a9e6a290-9f75-4cea-8c52-ee3dd0e01498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baduykiemthu</value>
      <webElementGuid>033dbbb9-72fd-45de-8d0c-bac918ddf983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_list&quot;)/tbody[1]/tr[1]/th[@class=&quot;field-username&quot;]/a[1]</value>
      <webElementGuid>85cd16e1-39b9-4a26-bbc1-0f64dff9ce31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/tbody/tr/th/a</value>
      <webElementGuid>01eaec26-ba1c-4f9c-a45a-dfd71de79df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'baduykiemthu')]</value>
      <webElementGuid>648310d9-93f1-4e34-8952-3529cbb1334e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff status'])[1]/following::a[1]</value>
      <webElementGuid>8510e42a-5340-48b1-bdac-1ee92e6d1e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::a[2]</value>
      <webElementGuid>f9a79bc6-35d4-424f-9775-08531120473c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nbduy@ctuet.edu.vn'])[1]/preceding::a[1]</value>
      <webElementGuid>4902dd7f-eeb8-4df4-9aae-359416048e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duy'])[1]/preceding::a[1]</value>
      <webElementGuid>7ff9fc48-6d4e-4fa4-b902-31a910e5cdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='baduykiemthu']/parent::*</value>
      <webElementGuid>32d88adb-5e33-47d7-861a-9f5543bb9b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/auth/user/2/change/')]</value>
      <webElementGuid>06421bba-0688-4394-85fc-4863a01a7f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/table/tbody/tr/th/a</value>
      <webElementGuid>c7e10d8c-526c-42ea-8bc6-7d9cdc365e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/auth/user/2/change/' and (text() = 'baduykiemthu' or . = 'baduykiemthu')]</value>
      <webElementGuid>bb509009-226e-4f41-99e9-3359f1de8cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
