<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug_slug</name>
   <tag></tag>
   <elementGuidId>094ff9bd-941f-442f-a7fc-7ab658aa7073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_slug</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_slug']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61d8accd-bc77-4e81-ba83-dfff75a1ca40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9397442e-00a2-4389-822f-d168b2d38e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slug</value>
      <webElementGuid>5e6bd9a3-ab43-4d3d-ab7b-662cfd94f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tivi</value>
      <webElementGuid>46df764a-ae31-4e6d-8ccc-7218664710f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vTextField</value>
      <webElementGuid>02344af9-afaa-46e0-98b2-0252bf518eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>19c1e963-b657-456a-acff-c069d28b7fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_slug</value>
      <webElementGuid>6b778d5c-476f-4de1-9bdd-029dbb3391dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_slug&quot;)</value>
      <webElementGuid>c4b8c880-c67b-4b5a-b090-60f4d16b2073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_slug']</value>
      <webElementGuid>d6aa751b-ae87-4b60-aa03-9cd727831db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='categogy_form']/div/fieldset/div[4]/div/div/input</value>
      <webElementGuid>d96d362c-67db-47e6-b6c2-f0c0b91833d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>781d43f1-c4e0-4dcb-8964-b287faecc123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'slug' and @id = 'id_slug']</value>
      <webElementGuid>5931f0e0-5c77-4c35-9d82-5f3c35883120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
