<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug__save</name>
   <tag></tag>
   <elementGuidId>19f772d1-b095-497f-b673-0ecf115b9ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f72fb6e-02f8-41da-a4eb-cfce0ddf3e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7bdbc8b4-3bad-4f96-be53-1589b95bfab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ec947725-4348-4111-a019-38d46e320386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>15125f68-ee70-4d2f-847f-f5e659cbd6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_save</value>
      <webElementGuid>7f8987ff-556c-4494-bdf9-8a2ce7fc3f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categogy_form&quot;)/div[1]/div[@class=&quot;submit-row&quot;]/input[@class=&quot;default&quot;]</value>
      <webElementGuid>e99b5f37-e359-47d8-abf5-de66a682f5d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_save']</value>
      <webElementGuid>b97d64ea-8aaa-431b-8cf7-b917aafdf022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='categogy_form']/div/div/input</value>
      <webElementGuid>8d6a0f9d-b208-4e95-8f53-7da0f24bbe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>35d79ab3-88b2-48f4-a935-29976c68c88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = '_save']</value>
      <webElementGuid>6529f8f9-cc1e-4b1f-9a20-61587313f650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
