<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_alert</name>
   <tag></tag>
   <elementGuidId>50a89f11-57d7-4ac2-8343-756e9f10676e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='categogy_form']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.errornote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5ba997c4-b691-4b9b-9633-f36634f18823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errornote</value>
      <webElementGuid>4e33b6b9-15b9-4704-a090-1a8f29e1852e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Please correct the error below.
    </value>
      <webElementGuid>a60e6873-a1c2-47cb-a51b-31eaf2437346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categogy_form&quot;)/div[1]/p[@class=&quot;errornote&quot;]</value>
      <webElementGuid>308cd236-904b-4991-a7d7-f60f2b95e2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='categogy_form']/div/p</value>
      <webElementGuid>c52c01ba-8dac-499a-bf61-a1c2ed66d41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add categogy'])[1]/following::p[1]</value>
      <webElementGuid>1dfcc37f-9cb1-4648-a328-d107d64f938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::p[1]</value>
      <webElementGuid>7b217bae-8205-4718-9c53-01aa94573175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub category:'])[1]/preceding::p[1]</value>
      <webElementGuid>6e5a80fc-f287-4800-b73d-1e7ae12507fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is sub'])[1]/preceding::p[1]</value>
      <webElementGuid>8527a337-930b-406e-b270-e545a63dd660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please correct the error below.']/parent::*</value>
      <webElementGuid>9c275ebc-e28b-4c0d-b6df-ad8f296cdd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>7913e6b3-0018-4317-8f06-226c2b2a4f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
    Please correct the error below.
    ' or . = '
    Please correct the error below.
    ')]</value>
      <webElementGuid>eccb661f-482d-4b7c-a5e7-33b6d99ea082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
