<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designates whether the user can log i_33faa1</name>
   <tag></tag>
   <elementGuidId>773117a3-fbe5-4c77-9dd5-441cc3d694cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_superuser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_superuser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d38d0669-1306-4d81-8871-213d0d278df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0cae71e5-380c-4f61-b111-7b551690ee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_superuser</value>
      <webElementGuid>ba5361e4-5493-4241-a8a8-26fcd3e2f464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_superuser_helptext</value>
      <webElementGuid>1fddbb38-aba1-4d52-a7bc-d1a8cc89b591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_superuser</value>
      <webElementGuid>e0a8ae8b-cb25-4355-b0be-083579fb4cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_superuser&quot;)</value>
      <webElementGuid>4f6cae3a-7913-470a-bc0a-e686d39c96ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_superuser']</value>
      <webElementGuid>0cc160f1-eb4b-47f2-aebe-dc5a355e1a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[3]/div/div/input</value>
      <webElementGuid>1606da42-2f30-43be-8d8f-fd2af6e206e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div/div/input</value>
      <webElementGuid>8ddbd5e2-75cf-49c9-bf83-4ef5486dee78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_superuser' and @id = 'id_is_superuser']</value>
      <webElementGuid>8a036d64-407d-4dff-9a99-1dc22ed2d354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
