<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_is_staff</name>
   <tag></tag>
   <elementGuidId>51a99262-8c1f-4907-8648-34efe2e0aedc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_is_staff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_is_staff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>249e23d7-7210-479b-9fab-5c6fd5681612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f191e3cd-e03d-41c8-95ff-116f171d3f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_staff</value>
      <webElementGuid>d56bb031-e92d-41c6-8d46-765e174b5e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_is_staff_helptext</value>
      <webElementGuid>fb66920c-f246-4973-b40b-bbe9a97141de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_is_staff</value>
      <webElementGuid>774d06bf-201b-46fc-b9fa-63892abd19b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_is_staff&quot;)</value>
      <webElementGuid>45db19c6-b560-4b7d-97fa-86d728a7a644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_is_staff']</value>
      <webElementGuid>f09040f5-d2d4-4e04-9eb5-f55bfd53557d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>48dbb4be-9a95-402b-b101-f96b21c0d712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>1261a6c0-ddba-403c-8b0b-72116a387cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_staff' and @id = 'id_is_staff']</value>
      <webElementGuid>cb42adf9-3bf5-4100-b420-e1dc34a42166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
