<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go_action-toggle</name>
   <tag></tag>
   <elementGuidId>7af6c091-c7fb-4493-8653-530e28c0c9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='action-toggle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23db4a36-7722-4705-8add-c34436fa42a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f980a808-177b-4ac7-b847-ce0fb79dce31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-toggle</value>
      <webElementGuid>c9f7edea-3178-45b2-8e99-3bd110c059d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select all objects on this page for an action</value>
      <webElementGuid>4e172745-d38f-4b24-8e70-6b022656b61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-toggle&quot;)</value>
      <webElementGuid>8c5b94ec-a2b8-4f0d-b819-962b2f1f5556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='action-toggle']</value>
      <webElementGuid>bca38d87-8223-4d1c-9c0d-1b074c653676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result_list']/thead/tr/th/div/span/input</value>
      <webElementGuid>54b7cf1e-bad1-424e-8ae9-7453653c238c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4e52b2ea-ddf8-4711-8117-0d7a20c0e0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'action-toggle']</value>
      <webElementGuid>68efcb81-3735-4c47-8bb2-8d589fff2791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
