<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_first_name</name>
   <tag></tag>
   <elementGuidId>e8b4c309-7902-4fef-8b63-d45786a81af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_first_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>febe4f80-cdc9-4c9a-8bad-c09a2e22b3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b410acd5-378c-4834-b234-d9923831e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>289a153d-df2a-44ab-a815-6255adbbaa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Duy</value>
      <webElementGuid>2f8f99f1-0dd3-4aeb-a334-addbf22763c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vTextField</value>
      <webElementGuid>e638cdb3-ddd1-4b4f-86dc-a8cd4be74c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>066d1173-4c00-409d-b110-5c3639ed19db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_first_name</value>
      <webElementGuid>99b4d968-1197-4ff5-b1b4-b95215df1ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_first_name&quot;)</value>
      <webElementGuid>8aa9d861-3a66-4a5d-8260-95071e54cf99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_first_name']</value>
      <webElementGuid>3761ae57-e378-405a-b0c7-4cd99aea7372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset[2]/div/div/div/input</value>
      <webElementGuid>b27aec99-8e62-4586-a495-a5b22e391d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/input</value>
      <webElementGuid>d5c11fdf-59b8-4b2d-901f-b22ec058001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'first_name' and @id = 'id_first_name']</value>
      <webElementGuid>a9f2add7-52a4-4c05-a3d5-3e50c0f7b3b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
