<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Username</name>
   <tag></tag>
   <elementGuidId>58b122d8-e2e1-4eb3-a03a-adfabaedd870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='user_form']/div/fieldset/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e99bbf54-9116-4998-8f30-6924430f81b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e81d714f-7719-490e-b1b6-1ad1beb198b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id_username</value>
      <webElementGuid>5e5fb3df-96ce-4246-ad71-82f67c361e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username:</value>
      <webElementGuid>bc144b69-9311-4422-b1be-d750ee306b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_form&quot;)/div[1]/fieldset[@class=&quot;module aligned&quot;]/div[@class=&quot;form-row field-username&quot;]/div[1]/div[@class=&quot;flex-container&quot;]/label[@class=&quot;required&quot;]</value>
      <webElementGuid>a10b8d25-9800-4953-a808-b01fc8264532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset/div/div/div/label</value>
      <webElementGuid>6a512aed-0074-411b-b6c2-19c05412d61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::label[1]</value>
      <webElementGuid>5bcdee27-5cad-48bb-81cd-1c72893f6b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='baduy'])[1]/following::label[1]</value>
      <webElementGuid>d0333c9c-d256-4e30-8d98-22a235efd50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'])[1]/preceding::label[1]</value>
      <webElementGuid>f8300e96-ecdb-4e1b-9f5f-fa6b501f240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/preceding::label[1]</value>
      <webElementGuid>56724f0b-8e75-4c52-8bed-704fd228df14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username:']/parent::*</value>
      <webElementGuid>c568eb14-6648-44ae-bf83-a597b4666aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>2e1b781f-3b48-4676-a34d-2338d476130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Username:' or . = 'Username:')]</value>
      <webElementGuid>ba485ec5-c3df-4201-85d8-24b23a38bd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
