<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password1</name>
   <tag></tag>
   <elementGuidId>2e649358-5028-488b-b7e7-75583734bf31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_password1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_password1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f8ab835-e9b8-4e44-9e5f-badca73d7d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b2fb2fdf-1ade-4102-a7f2-96652b26eb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password1</value>
      <webElementGuid>826c027d-8ac8-4a2f-89ba-9987a547d9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>4a0a3836-f19a-4523-8831-c24d6a0c6c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id_password1_helptext</value>
      <webElementGuid>a0ea3ac2-93a9-4f11-a773-6696b9f98044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_password1</value>
      <webElementGuid>84ddaa4e-41a9-42a4-ba14-b015cc394658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_password1&quot;)</value>
      <webElementGuid>d3aa4b87-1dc0-4a63-831a-20cf35ae8665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_password1']</value>
      <webElementGuid>20ca22c5-609f-4753-9ba4-04b895f895e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user_form']/div/fieldset/div[3]/div/div/input</value>
      <webElementGuid>a7312b53-9645-4812-9ee7-846d1c00d78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c91fcd19-212e-47d8-9a9f-a6fd5c7ec377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password1' and @id = 'id_password1']</value>
      <webElementGuid>b512b437-f39a-46bc-b7e0-ebc25e1b3f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
